# Generated by Django 6.0.3 on 2026-04-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='first_publish_year',
            new_name='publish_year',
        ),
    ]
