# Generated by Django 6.0.3 on 2026-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_first_publish_year_book_publish_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_year',
            new_name='first_publish_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='author_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
