# Generated by Django 6.0.3 on 2026-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_book_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_key',
        ),
    ]
