# Generated by Django 6.0.3 on 2026-04-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
